#############################################################################
# Makefile for building: dicto
# Generated by qmake (2.01a) (Qt 4.5.2) on: sob. lut 13 21:31:08 2010
# Project:  dicto.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile dicto.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iobj
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = cdocument.cpp \
		centry.cpp \
		main.cpp \
		wabout.cpp \
		wdialog.cpp \
		wmain.cpp \
		wmain_test.cpp \
		wmain_exam.cpp \
		wmain_utils.cpp \
		wprepare.cpp \
		wprops.cpp \
		wprint.cpp \
		wsettings.cpp obj/moc_wabout.cpp \
		obj/moc_wdialog.cpp \
		obj/moc_wmain.cpp \
		obj/moc_wprepare.cpp \
		obj/moc_wprops.cpp \
		obj/moc_wprint.cpp \
		obj/moc_wsettings.cpp \
		obj/qrc_dicto.cpp
OBJECTS       = obj/cdocument.o \
		obj/centry.o \
		obj/main.o \
		obj/wabout.o \
		obj/wdialog.o \
		obj/wmain.o \
		obj/wmain_test.o \
		obj/wmain_exam.o \
		obj/wmain_utils.o \
		obj/wprepare.o \
		obj/wprops.o \
		obj/wprint.o \
		obj/wsettings.o \
		obj/moc_wabout.o \
		obj/moc_wdialog.o \
		obj/moc_wmain.o \
		obj/moc_wprepare.o \
		obj/moc_wprops.o \
		obj/moc_wprint.o \
		obj/moc_wsettings.o \
		obj/qrc_dicto.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		dicto.pro
QMAKE_TARGET  = dicto
DESTDIR       = 
TARGET        = dicto

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dicto.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile dicto.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile dicto.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/dicto1.0.0 || $(MKDIR) obj/dicto1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/dicto1.0.0/ && $(COPY_FILE) --parents cdocument.h centry.h wabout.h wdialog.h wmain.h wprepare.h wprops.h wprint.h wsettings.h obj/dicto1.0.0/ && $(COPY_FILE) --parents resources/dicto.qrc obj/dicto1.0.0/ && $(COPY_FILE) --parents cdocument.cpp centry.cpp main.cpp wabout.cpp wdialog.cpp wmain.cpp wmain_test.cpp wmain_exam.cpp wmain_utils.cpp wprepare.cpp wprops.cpp wprint.cpp wsettings.cpp obj/dicto1.0.0/ && $(COPY_FILE) --parents translations/dicto_pl.ts translations/dicto_ru.ts obj/dicto1.0.0/ && (cd `dirname obj/dicto1.0.0` && $(TAR) dicto1.0.0.tar dicto1.0.0 && $(COMPRESS) dicto1.0.0.tar) && $(MOVE) `dirname obj/dicto1.0.0`/dicto1.0.0.tar.gz . && $(DEL_FILE) -r obj/dicto1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: obj/moc_wabout.cpp obj/moc_wdialog.cpp obj/moc_wmain.cpp obj/moc_wprepare.cpp obj/moc_wprops.cpp obj/moc_wprint.cpp obj/moc_wsettings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_wabout.cpp obj/moc_wdialog.cpp obj/moc_wmain.cpp obj/moc_wprepare.cpp obj/moc_wprops.cpp obj/moc_wprint.cpp obj/moc_wsettings.cpp
obj/moc_wabout.cpp: wabout.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wabout.h -o obj/moc_wabout.cpp

obj/moc_wdialog.cpp: wmain.h \
		cdocument.h \
		centry.h \
		wabout.h \
		wdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wdialog.h -o obj/moc_wdialog.cpp

obj/moc_wmain.cpp: cdocument.h \
		centry.h \
		wabout.h \
		wmain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wmain.h -o obj/moc_wmain.cpp

obj/moc_wprepare.cpp: wprepare.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wprepare.h -o obj/moc_wprepare.cpp

obj/moc_wprops.cpp: wprops.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wprops.h -o obj/moc_wprops.cpp

obj/moc_wprint.cpp: wprint.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wprint.h -o obj/moc_wprint.cpp

obj/moc_wsettings.cpp: wsettings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wsettings.h -o obj/moc_wsettings.cpp

compiler_rcc_make_all: obj/qrc_dicto.cpp
compiler_rcc_clean:
	-$(DEL_FILE) obj/qrc_dicto.cpp
obj/qrc_dicto.cpp: resources/dicto.qrc \
		resources/dictologo.png \
		resources/pewniak747.jpg
	/usr/bin/rcc -name dicto resources/dicto.qrc -o obj/qrc_dicto.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

obj/cdocument.o: cdocument.cpp cdocument.h \
		centry.h \
		wmain.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cdocument.o cdocument.cpp

obj/centry.o: centry.cpp centry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/centry.o centry.cpp

obj/main.o: main.cpp wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/wabout.o: wabout.cpp wabout.h \
		wmain.h \
		cdocument.h \
		centry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wabout.o wabout.cpp

obj/wdialog.o: wdialog.cpp wdialog.h \
		wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wdialog.o wdialog.cpp

obj/wmain.o: wmain.cpp wmain.h \
		cdocument.h \
		centry.h \
		wabout.h \
		wdialog.h \
		wprepare.h \
		wsettings.h \
		wprops.h \
		wprint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wmain.o wmain.cpp

obj/wmain_test.o: wmain_test.cpp wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wmain_test.o wmain_test.cpp

obj/wmain_exam.o: wmain_exam.cpp wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wmain_exam.o wmain_exam.cpp

obj/wmain_utils.o: wmain_utils.cpp wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wmain_utils.o wmain_utils.cpp

obj/wprepare.o: wprepare.cpp wprepare.h \
		cdocument.h \
		centry.h \
		wmain.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wprepare.o wprepare.cpp

obj/wprops.o: wprops.cpp wprops.h \
		wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wprops.o wprops.cpp

obj/wprint.o: wprint.cpp wprint.h \
		wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wprint.o wprint.cpp

obj/wsettings.o: wsettings.cpp wsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wsettings.o wsettings.cpp

obj/moc_wabout.o: obj/moc_wabout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_wabout.o obj/moc_wabout.cpp

obj/moc_wdialog.o: obj/moc_wdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_wdialog.o obj/moc_wdialog.cpp

obj/moc_wmain.o: obj/moc_wmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_wmain.o obj/moc_wmain.cpp

obj/moc_wprepare.o: obj/moc_wprepare.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_wprepare.o obj/moc_wprepare.cpp

obj/moc_wprops.o: obj/moc_wprops.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_wprops.o obj/moc_wprops.cpp

obj/moc_wprint.o: obj/moc_wprint.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_wprint.o obj/moc_wprint.cpp

obj/moc_wsettings.o: obj/moc_wsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_wsettings.o obj/moc_wsettings.cpp

obj/qrc_dicto.o: obj/qrc_dicto.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_dicto.o obj/qrc_dicto.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

