#############################################################################
# Makefile for building: dicto
# Generated by qmake (2.01a) (Qt 4.5.2) on: pon. gru 14 19:48:25 2009
# Project:  dicto.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile dicto.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cdocument.cpp \
		centry.cpp \
		main.cpp \
		wabout.cpp \
		wdialog.cpp \
		wmain.cpp \
		wprepare.cpp \
		wprops.cpp \
		wprint.cpp moc_cdocument.cpp \
		moc_wabout.cpp \
		moc_wdialog.cpp \
		moc_wmain.cpp \
		moc_wprepare.cpp \
		moc_wprops.cpp \
		moc_wprint.cpp \
		qrc_dicto.cpp
OBJECTS       = cdocument.o \
		centry.o \
		main.o \
		wabout.o \
		wdialog.o \
		wmain.o \
		wprepare.o \
		wprops.o \
		wprint.o \
		moc_cdocument.o \
		moc_wabout.o \
		moc_wdialog.o \
		moc_wmain.o \
		moc_wprepare.o \
		moc_wprops.o \
		moc_wprint.o \
		qrc_dicto.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		dicto.pro
QMAKE_TARGET  = dicto
DESTDIR       = 
TARGET        = dicto

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dicto.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile dicto.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile dicto.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/dicto1.0.0 || $(MKDIR) .tmp/dicto1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dicto1.0.0/ && $(COPY_FILE) --parents cdocument.h centry.h wabout.h wdialog.h wmain.h wprepare.h wprops.h wprint.h .tmp/dicto1.0.0/ && $(COPY_FILE) --parents resources/dicto.qrc .tmp/dicto1.0.0/ && $(COPY_FILE) --parents cdocument.cpp centry.cpp main.cpp wabout.cpp wdialog.cpp wmain.cpp wprepare.cpp wprops.cpp wprint.cpp .tmp/dicto1.0.0/ && $(COPY_FILE) --parents translations/dicto_pl.ts .tmp/dicto1.0.0/ && (cd `dirname .tmp/dicto1.0.0` && $(TAR) dicto1.0.0.tar dicto1.0.0 && $(COMPRESS) dicto1.0.0.tar) && $(MOVE) `dirname .tmp/dicto1.0.0`/dicto1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dicto1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cdocument.cpp moc_wabout.cpp moc_wdialog.cpp moc_wmain.cpp moc_wprepare.cpp moc_wprops.cpp moc_wprint.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cdocument.cpp moc_wabout.cpp moc_wdialog.cpp moc_wmain.cpp moc_wprepare.cpp moc_wprops.cpp moc_wprint.cpp
moc_cdocument.cpp: centry.h \
		cdocument.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cdocument.h -o moc_cdocument.cpp

moc_wabout.cpp: wabout.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wabout.h -o moc_wabout.cpp

moc_wdialog.cpp: wmain.h \
		cdocument.h \
		centry.h \
		wabout.h \
		wdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wdialog.h -o moc_wdialog.cpp

moc_wmain.cpp: cdocument.h \
		centry.h \
		wabout.h \
		wmain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wmain.h -o moc_wmain.cpp

moc_wprepare.cpp: wprepare.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wprepare.h -o moc_wprepare.cpp

moc_wprops.cpp: wprops.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wprops.h -o moc_wprops.cpp

moc_wprint.cpp: wprint.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wprint.h -o moc_wprint.cpp

compiler_rcc_make_all: qrc_dicto.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_dicto.cpp
qrc_dicto.cpp: resources/dicto.qrc \
		resources/dictologo.png \
		resources/pewniak747.jpg
	/usr/bin/rcc -name dicto resources/dicto.qrc -o qrc_dicto.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

cdocument.o: cdocument.cpp cdocument.h \
		centry.h \
		wmain.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cdocument.o cdocument.cpp

centry.o: centry.cpp centry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o centry.o centry.cpp

main.o: main.cpp wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

wabout.o: wabout.cpp wabout.h \
		wmain.h \
		cdocument.h \
		centry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wabout.o wabout.cpp

wdialog.o: wdialog.cpp wdialog.h \
		wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wdialog.o wdialog.cpp

wmain.o: wmain.cpp wmain.h \
		cdocument.h \
		centry.h \
		wabout.h \
		wdialog.h \
		wprepare.h \
		wprops.h \
		wprint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wmain.o wmain.cpp

wprepare.o: wprepare.cpp wprepare.h \
		cdocument.h \
		centry.h \
		wmain.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wprepare.o wprepare.cpp

wprops.o: wprops.cpp wprops.h \
		wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wprops.o wprops.cpp

wprint.o: wprint.cpp wprint.h \
		wmain.h \
		cdocument.h \
		centry.h \
		wabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wprint.o wprint.cpp

moc_cdocument.o: moc_cdocument.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cdocument.o moc_cdocument.cpp

moc_wabout.o: moc_wabout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wabout.o moc_wabout.cpp

moc_wdialog.o: moc_wdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wdialog.o moc_wdialog.cpp

moc_wmain.o: moc_wmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wmain.o moc_wmain.cpp

moc_wprepare.o: moc_wprepare.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wprepare.o moc_wprepare.cpp

moc_wprops.o: moc_wprops.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wprops.o moc_wprops.cpp

moc_wprint.o: moc_wprint.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wprint.o moc_wprint.cpp

qrc_dicto.o: qrc_dicto.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_dicto.o qrc_dicto.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

